spring:
  application:
    name: travelapi
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

rapidapi:
  booking:
    base-url: ${RAPIDAPI_BOOKING_URL}
    key: ${RAPIDAPI_KEY}
    host: ${RAPIDAPI_HOST}

weather:
  open-meteo:
    base-url: ${WEATHER_OPEN_METEO_BASE_URL}
    cache-ttl-hours: ${WEATHER_CACHE_TTL_HOURS}

jwt:
  secret: ${JWT_SECRET}
  expiration-seconds: ${JWT_EXPIRATION_SECONDS}
  refresh-token-expiration-days: ${JWT_REFRESH_TOKEN_EXPIRATION_DAYS}

google:
  client-id: ${GOOGLE_CLIENT_ID}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

